# coding:utf-8
"""
Django settings for aeplus project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import sys
reload(sys)
sys.setdefaultencoding("utf-8")
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^^vz1e=$6gwdi=v%^qb=bs4&o(&s)^lr7rkhahr(=d^j(blk5x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'institute',
    'partner',
    'prolib',
    'resource',
    'subscribe',
    'DjangoUeditor',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'aeplus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aeplus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'aeplus',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL='/'
MEDIA_ROOT=os.path.join(BASE_DIR, '')

DATETIME_FORMAT = 'Y-m-d H:i:s'
DATE_FORMAT = 'Y-m-d'
SUIT_CONFIG = {
    'ADMIN_NAME': 'AeternityPlus',
    'HEADER_DATE_FORMAT': 'Y年m月j日 l',
    'HEADER_TIME_FORMAT': 'H:i',
    'MENU': (
             {'label': '研究院管理',
              'app': 'institute',
              'models': ('Instituteclass','Instituteinfo','Schoolinfo',)
              },
             {'label': '合作伙伴管理',
              'app': 'partner',
              'models': ('Partnerinfo',)
              },
             {'label': '项目库管理',
              'app': 'prolib',
              'models': ('Prolibclass','Prolibinfo',)
              },
             {'label': '资源管理',
              'app': 'resource',
              'models': ('Resourceclass','Resourceinfo',)
              },
             {'label': '博客管理',
              'app': 'blog',
              'models': ('Blogclass','Bloginfo',)
              },
             {'label': '订阅管理',
              'app': 'subscribe',
              'models': ('SubscribeUserList', 'Subscribeinfo',)
              },
             ),

}

# SMTP_SERVER = 'smtp.qq.com'
# FROM_ADDR = '2860847900@qq.com'
# PASSWORD = 'pkliopftothjdhcc'
SMTP_SERVER = 'smtp.gmail.com'
FROM_ADDR = 'julyorangesae@gmail.com'
PASSWORD = 'liujiacheng123'

